cluster: "moab-submit.py --depend \"{dependencies}\""
cluster-status: "moab-status.py"
jobscript: "moab-jobscript.sh"
jobs: 5000
immediate-submit: {{cookiecutter.immediate_submit}}
verbose: true
notemp: true
